/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

group = "org.emi.json"
version = "0.1.0"

plugins {
    `java-library`
    id("me.champeau.jmh") version "0.7.3"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // 1. Esto permite que el benchmark vea las clases de src/main/java (FastJson)
    "jmhImplementation"(project(":lib")) 
    
    // 2. JMH Core
    "jmhImplementation"("org.openjdk.jmh:jmh-core:1.37")
    
    // 3. Procesador de anotaciones (CRÍTICO para generar el código de medición)
    "jmhAnnotationProcessor"("org.openjdk.jmh:jmh-generator-annprocess:1.37")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("6.0.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jmh {
    warmupIterations.set(3)
    iterations.set(5)
    fork.set(1)
    //benchmarkMode.set(listOf("thrpt"))
    benchmarkMode.set(listOf("avgt"))
    resultFormat.set("TEXT")
    //profilers.set(listOf("jfr"))
    
    // ESTO ES LO QUE FALTA PARA EL VECTOR API EN EL BENCHMARK
    jvmArgs.set(listOf("--add-modules", "jdk.incubator.vector"))
}

// 3. Flags de compilación (Afecta a la librería)
tasks.withType<JavaCompile> {
    options.compilerArgs.addAll(listOf("--add-modules", "jdk.incubator.vector"))
}


// Forzamos la configuración específicamente para la tarea 'run' del plugin application
tasks.withType<JavaExec> {
    jvmArgs("--add-modules", "jdk.incubator.vector")
}

// 5. Flags para Tests
tasks.withType<Test> {
    jvmArgs("--add-modules", "jdk.incubator.vector")
}
